### PR TITLE
Bubble Sort Implementation Program C++

### LINKED ISSUE #4: Bubble Sort Implementation Program C++

### PR DESCRIPTION
**Pull request by ayushgupta0110**
Fixed #4

### CODE REVIEW

**Comment by chinmaypant21** [comment]
All good, but there are some redundant parts of code, like extra libraries included (iostream is sufficient on its own) and swap function (c++ gives inbuilt swap function ).
And one small thing, can you please remove unnecessary comments from it and provide the alternative of a while loop for continuous inputs. That's it.
Can you please fix them?

**Comment by ayushgupta0110** [comment]
Ya I will fix these issues

**Comment by ayushgupta0110** [comment]
Do check if anything else I need to change. I added the time header file because of generating random values.

**Comment by chinmaypant21** [comment]
Great

**Pull request merged**
